//---------------------------------------------------------------------------

#ifndef Unit1H
#define Unit1H
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <ExtCtrls.hpp>
#include <ComCtrls.hpp>
#include <CheckLst.hpp>
#include <Menus.hpp>
#include <ScktComp.hpp>
#include <Buttons.hpp>
#include <ButtonGroup.hpp>
#include <jpeg.hpp>
#include <Dialogs.hpp>
#include <ImgList.hpp>
#include <AppEvnts.hpp>
#include <OleCtrls.hpp>
#include <SHDocVw.hpp>
#include <vector>
//---------------------------------------------------------------------------
//extern char DosyaYol[MAX_PATH];
extern String HDDNO;




class TForm1 : public TForm
{
__published:	// IDE-managed Components
	TPopupMenu *PopupMenu2;
	TMenuItem *Sell1;
	TMenuItem *Crash1;
	TMenuItem *SellItem1;
	TMenuItem *SellItem2;
	TMenuItem *CrashItem1;
	TMenuItem *SellAll1;
	TMenuItem *Deneme1;
	TMainMenu *MainMenu1;
	TMenuItem *Menuu;
	TMenuItem *ConnectAll1;
	TMenuItem *DisconnectAll1;
	TMenuItem *AllTOwn1;
	TMenuItem *AllGo1;
	TPopupMenu *PopupMenu1;
	TMenuItem *Connect9;
	TMenuItem *Move9;
	TMenuItem *Party2;
	TMenuItem *own1;
	TMenuItem *Coordinate9;
	TMenuItem *Add2;
	TMenuItem *Add3;
	TMenuItem *Quit2;
	TMenuItem *Exit1;
	TMenuItem *Mine1;
	TMenuItem *Start1;
	TMenuItem *GoToRepair1;
	TMenuItem *Atack1;
	TMenuItem *Start2;
	TClientSocket *ClientSocket1;
	TMenuItem *Wear1;
	TMenuItem *LeftHand1;
	TMenuItem *RightHand1;
	TMenuItem *Move10;
	TMenuItem *rade1;
	TMenuItem *T1;
	TMenuItem *radeAccept1;
	TMenuItem *radeConfirm1;
	TMenuItem *AddThisItem1;
	TMenuItem *AddMoney1;
	TMenuItem *radeCancel1;
	TMenuItem *GiveList1;
	TMenuItem *AddList1;
	TMenuItem *Sell2;
	TMenuItem *Crash2;
	TMenuItem *rade2;
	TMenuItem *radeAll1;
	TMenuItem *toSocket11;
	TMenuItem *toSocket1;
	TMenuItem *toSocket31;
	TMenuItem *toSocket32;
	TMenuItem *toSocket41;
	TMenuItem *toSocket51;
	TMenuItem *toSocket61;
	TMenuItem *toSocket71;
	TListBox *log;
	TImageList *ImageList1;
	TMenuItem *Disconnect1;
	TMenuItem *GoPitman1;
	TMenuItem *Stop1;
	TMenuItem *Stop2;
	TMenuItem *PARTYtP1;
	TMenuItem *GoPotion1;
	TTimer *Timer2;
	TTimer *Timer3;
	TMenuItem *AllAtack1;
	TMenuItem *Start3;
	TMenuItem *Stop3;
	TMenuItem *Coordinate1;
	TMenuItem *StopALl1;
	TTimer *Timer1;
	TMenuItem *Potion1;
	TPageControl *PageControl1;
	TTabSheet *TabSheet3;
	TGroupBox *GroupBox3;
	TListBox *LetterItem;
	TListBox *LetterAdet;
	TListBox *LetterId;
	TButton *LetterKontrol;
	TButton *SeciliLCek;
	TCheckBox *OtoLetterCek;
	TCheckBox *TradeAc;
	TEdit *Edit3;
	TGroupBox *GroupBox1;
	TLabel *Label1;
	TLabel *Label2;
	TEdit *Edit1;
	TEdit *Edit2;
	TButton *Button5;
	TCheckBox *ototo;
	TGroupBox *GroupBox43;
	TEdit *cMail;
	TEdit *cPassword;
	TEdit *cUsername;
	TEdit *cNick;
	TButton *Register;
	TTabSheet *TabSheet1;
	TButton *Button79;
	TTabSheet *TabSheet6;
	TImage *Image1;
	TButton *Button3;
	TGroupBox *GroupBox4;
	TListBox *SellList;
	TGroupBox *GroupBox5;
	TListBox *CrashList;
	TGroupBox *GroupBox6;
	TListBox *TradeList;
	TButton *Button6;
	TButton *Button11;
	TButton *Button88;
	TTabSheet *TabSheet4;
	TGroupBox *GroupBox7;
	TLabel *Label10;
	TLabel *Label11;
	TLabel *Label12;
	TLabel *Label13;
	TLabel *Label14;
	TLabel *Label15;
	TButton *Button4;
	TButton *Button7;
	TButton *Button8;
	TButton *Button9;
	TButton *Button10;
	TGroupBox *GroupBox8;
	TLabel *Label16;
	TLabel *Label17;
	TLabel *Label18;
	TLabel *Label19;
	TLabel *Label20;
	TLabel *Label21;
	TButton *Button12;
	TButton *Button13;
	TButton *Button14;
	TButton *Button15;
	TButton *Button16;
	TGroupBox *GroupBox9;
	TLabel *Label22;
	TLabel *Label23;
	TLabel *Label24;
	TLabel *Label25;
	TLabel *Label26;
	TLabel *Label27;
	TButton *Button17;
	TButton *Button18;
	TButton *Button19;
	TButton *Button20;
	TButton *Button21;
	TGroupBox *GroupBox10;
	TLabel *Label28;
	TLabel *Label29;
	TLabel *Label30;
	TLabel *Label31;
	TLabel *Label32;
	TLabel *Label33;
	TButton *Button22;
	TButton *Button23;
	TButton *Button24;
	TButton *Button25;
	TButton *Button26;
	TGroupBox *GroupBox11;
	TLabel *Label34;
	TLabel *Label35;
	TLabel *Label36;
	TLabel *Label37;
	TLabel *Label38;
	TLabel *Label39;
	TButton *Button27;
	TButton *Button28;
	TButton *Button29;
	TButton *Button30;
	TButton *Button31;
	TGroupBox *GroupBox12;
	TLabel *Label40;
	TLabel *Label41;
	TLabel *Label42;
	TLabel *Label43;
	TLabel *Label44;
	TLabel *Label45;
	TButton *Button32;
	TButton *Button33;
	TButton *Button34;
	TButton *Button35;
	TButton *Button36;
	TGroupBox *GroupBox13;
	TLabel *Label46;
	TLabel *Label47;
	TLabel *Label48;
	TLabel *Label49;
	TLabel *Label50;
	TLabel *Label51;
	TButton *Button37;
	TButton *Button38;
	TButton *Button39;
	TButton *Button40;
	TButton *Button41;
	TGroupBox *GroupBox14;
	TLabel *Label52;
	TLabel *Label53;
	TLabel *Label54;
	TLabel *Label55;
	TLabel *Label56;
	TLabel *Label57;
	TButton *Button42;
	TButton *Button43;
	TButton *Button44;
	TButton *Button45;
	TButton *Button46;
	TGroupBox *GroupBox15;
	TLabel *Label58;
	TLabel *Label59;
	TLabel *Label60;
	TLabel *Label61;
	TLabel *Label62;
	TButton *Button47;
	TButton *Button48;
	TButton *Button49;
	TButton *Button50;
	TGroupBox *GroupBox16;
	TLabel *Label63;
	TLabel *Label64;
	TLabel *Label65;
	TLabel *Label66;
	TLabel *Label67;
	TButton *Button51;
	TButton *Button52;
	TButton *Button53;
	TButton *Button54;
	TGroupBox *GroupBox17;
	TLabel *Label68;
	TLabel *Label69;
	TLabel *Label70;
	TLabel *Label71;
	TLabel *Label72;
	TButton *Button55;
	TButton *Button56;
	TButton *Button57;
	TButton *Button58;
	TGroupBox *GroupBox18;
	TLabel *Label73;
	TLabel *Label74;
	TLabel *Label75;
	TLabel *Label76;
	TLabel *Label77;
	TButton *Button59;
	TButton *Button60;
	TButton *Button61;
	TButton *Button62;
	TGroupBox *GroupBox19;
	TLabel *Label78;
	TLabel *Label79;
	TLabel *Label80;
	TLabel *Label81;
	TLabel *Label82;
	TButton *Button63;
	TButton *Button64;
	TButton *Button65;
	TButton *Button66;
	TGroupBox *GroupBox20;
	TLabel *Label83;
	TLabel *Label84;
	TLabel *Label85;
	TLabel *Label86;
	TLabel *Label87;
	TButton *Button67;
	TButton *Button68;
	TButton *Button69;
	TButton *Button70;
	TGroupBox *GroupBox21;
	TLabel *Label88;
	TLabel *Label89;
	TLabel *Label90;
	TLabel *Label91;
	TLabel *Label92;
	TButton *Button71;
	TButton *Button72;
	TButton *Button73;
	TButton *Button74;
	TGroupBox *GroupBox22;
	TLabel *Label93;
	TLabel *Label94;
	TLabel *Label95;
	TLabel *Label96;
	TLabel *Label97;
	TButton *Button75;
	TButton *Button76;
	TButton *Button77;
	TButton *Button78;
	TButton *st1job;
	TGroupBox *GroupBox23;
	TListBox *ListBox1;
	TEdit *Edit4;
	TEdit *Edit5;
	TButton *Button2;
	TListBox *ListBox2;
	TCheckBox *CheckBox1;
	TCheckBox *CheckBox2;
	TCheckBox *CheckBox3;
	TCheckBox *CheckBox4;
	TCheckBox *CheckBox5;
	TCheckBox *CheckBox6;
	TCheckBox *CheckBox7;
	TCheckBox *CheckBox8;
	TGroupBox *GroupBox31;
	TLabel *Label98;
	TEdit *Edit20;
	TButton *Button86;
	TButton *Dolas;
	TButton *Button82;
	TTabSheet *TabSheet2;
	TCheckListBox *BuffSkillList;
	TCheckListBox *HealList;
	TRadioGroup *AtackType;
	TGroupBox *GroupBox46;
	TListBox *ListBox4;
	TListBox *ListBox5;
	TListBox *ListBox6;
	TListBox *ListBox7;
	TMemo *Memo9;
	TListBox *ListBox8;
	TButton *Button94;
	TButton *Button95;
	TButton *Button96;
	TButton *Button97;
	TButton *Button98;
	TTabSheet *TabSheet5;
	TListBox *ListBoxtt;
	TListBox *HealSkillKod;
	TListBox *BuffSkillKod;
	TRadioGroup *RadioGroup2;
	TCheckBox *CheckBox9;
	TButton *Button85;
	TEdit *Edit6;
	TEdit *Edit7;
	TButton *Button87;
	TListBox *ListBox3;
	TButton *Button1;
	TRadioGroup *RadioGroup4;
	TRadioGroup *RadioGroup5;
	TRadioGroup *RadioGroup6;
	TButton *Button92;
	TButton *Button93;
	TTabSheet *TabSheet7;
	TButton *inngetir;
	TEdit *innpage;
	TTabSheet *TabSheet8;
	TGroupBox *GroupBox45;
	TListBox *ListBox9;
	TListBox *ListBox10;
	TListBox *ListBox11;
	TListBox *ListBox12;
	TMemo *Memo10;
	TListBox *ListBox13;
	TButton *Button99;
	TButton *Button100;
	TButton *Button101;
	TButton *Button102;
	TButton *Button103;
	TGroupBox *GroupBox47;
	TListBox *ListBox14;
	TListBox *ListBox15;
	TListBox *ListBox16;
	TListBox *ListBox17;
	TMemo *Memo11;
	TListBox *ListBox18;
	TButton *Button104;
	TButton *Button105;
	TButton *Button106;
	TButton *Button107;
	TButton *Button108;
	TGroupBox *GroupBox48;
	TListBox *ListBox19;
	TListBox *ListBox20;
	TListBox *ListBox21;
	TListBox *ListBox22;
	TMemo *Memo12;
	TListBox *ListBox23;
	TButton *Button109;
	TButton *Button110;
	TButton *Button111;
	TButton *Button112;
	TButton *Button113;
	TGroupBox *GroupBox49;
	TListBox *ListBox24;
	TListBox *ListBox25;
	TListBox *ListBox26;
	TListBox *ListBox27;
	TMemo *Memo13;
	TListBox *ListBox28;
	TButton *Button114;
	TButton *Button115;
	TButton *Button116;
	TButton *Button117;
	TButton *Button118;
	TGroupBox *GroupBox50;
	TListBox *ListBox29;
	TListBox *ListBox30;
	TListBox *ListBox31;
	TListBox *ListBox32;
	TMemo *Memo14;
	TListBox *ListBox33;
	TButton *Button119;
	TButton *Button120;
	TButton *Button121;
	TButton *Button122;
	TButton *Button123;
	TGroupBox *GroupBox51;
	TListBox *ListBox34;
	TListBox *ListBox35;
	TListBox *ListBox36;
	TListBox *ListBox37;
	TMemo *Memo15;
	TListBox *ListBox38;
	TButton *Button124;
	TButton *Button125;
	TButton *Button126;
	TButton *Button127;
	TButton *Button128;
	TGroupBox *GroupBox52;
	TListBox *ListBox39;
	TListBox *ListBox40;
	TListBox *ListBox41;
	TListBox *ListBox42;
	TMemo *Memo16;
	TListBox *ListBox43;
	TButton *Button129;
	TButton *Button130;
	TButton *Button131;
	TButton *Button132;
	TButton *Button133;
	TMenuItem *Helmet1;
	TMenuItem *Pauldron1;
	TMenuItem *Pads1;
	TMenuItem *Bots1;
	TMenuItem *Bots2;
	TMenuItem *Earring01;
	TMenuItem *Earring11;
	TMenuItem *Pendant1;
	TMenuItem *Belt1;
	TMenuItem *Ring01;
	TMenuItem *Ring1;
	TCheckBox *AllSameSkill;
	TRadioGroup *buybow;
	TButton *Button134;
	TCheckListBox *BuyBowSocks;
	TListBox *ListBox44;
	TButton *Button135;
	TButton *Button141;
	TButton *Button142;
	TButton *Button143;
	TButton *Button144;
	TButton *Button145;
	TButton *Button146;
	TButton *Button147;
	TButton *Button148;
	TButton *Button149;
	TButton *Button150;
	TButton *Button151;
	TButton *Button152;
	TButton *Button153;
	TButton *Button154;
	TButton *Button155;
	TButton *Button156;
	TButton *Button157;
	TButton *Button158;
	TButton *Button159;
	TButton *Button160;
	TButton *Button161;
	TButton *Button162;
	TButton *Button163;
	TButton *Button164;
	TButton *Button165;
	TButton *Button166;
	TButton *Button167;
	TButton *Button168;
	TButton *Button169;
	TButton *Button170;
	TButton *Button171;
	TButton *Button172;
	TButton *Button173;
	TButton *Button174;
	TButton *Button175;
	TButton *Button176;
	TButton *Button177;
	TButton *Button178;
	TButton *Button179;
	TButton *Button180;
	TGroupBox *GroupBox53;
	TLabel *Label8;
	TButton *Button182;
	TMemo *Mesaj;
	TEdit *Edit8;
	TRadioGroup *ChatTipi;
	TCheckBox *PM;
	TCheckListBox *ChatList;
	TClientSocket *ClientSocket2;
	TTimer *Timer4;
	TClientSocket *ClientSocket3;
	TTimer *Timer5;
	TLabel *spdlbl;
	TButton *AllPtOk;
	TButton *AllPtQuit;
	TButton *AllTown;
	TButton *KazBasla;
	TButton *KazDur;
	TRadioGroup *Trade;
	TGroupBox *GroupBox32;
	TEdit *spcode;
	TCheckBox *RunToMob;
	TRadioGroup *AutoClan;
	TGroupBox *GroupBox2;
	TLabel *Label3;
	TEdit *MineY;
	TEdit *MineX;
	TButton *Button81;
	TCheckBox *RAtack;
	TCheckBox *CheckBox10;
	TCheckBox *CheckBox11;
	TGroupBox *GroupBox30;
	TLabel *Label4;
	TLabel *Label5;
	TEdit *AtackY;
	TEdit *AtackX;
	TEdit *distance;
	TGroupBox *GroupBox44;
	TLabel *Label6;
	TLabel *Label7;
	TEdit *hpcount;
	TEdit *mpcount;
	TButton *Button90;
	TButton *Button89;
	TScrollBar *SpeedSet;
	TButton *Button91;
	TButton *Button80;
	TButton *Button83;
	TCheckBox *CheckBox12;
	TButton *Button84;
	TButton *Button136;
	TButton *Button137;
	TButton *Button138;
	TCheckBox *paraver;
	TButton *Button187;
	TButton *Button139;
	TMenuItem *SocketReset1;
	TButton *Button185;
	TComboBox *allsrv;
	TComboBox *allloc;
	TMemo *Memo1;
	TEdit *Edit11;
	TButton *AllPressOk;
	TButton *Button184;
	TEdit *Edit9;
	TButton *Button183;
	TEdit *Edit10;
	TButton *Button186;
	TCheckBox *CheckBox13;
	TCheckBox *AutoExp;
	TCheckBox *CheckBox14;
	TCheckBox *CheckBox15;
	TCheckBox *proxy;
	TCheckBox *CheckBox16;
	TButton *Button140;
	TEdit *Edit12;
	TTimer *Timer6;
	TCheckBox *CheckBox18;
	TTimer *Timer7;
	TButton *Button181;
	TButton *Button188;
	TButton *Button189;
	TEdit *Edit13;
	TEdit *Edit14;
	TButton *Button190;
	TButton *Button191;
	TCheckBox *CheckBox17;
	TButton *Button192;
	TEdit *Edit15;
	TButton *Button193;
	TButton *Button194;
	TButton *Button198;
	TButton *Button199;
	TMemo *Memo2;
	TListBox *ListBox45;
	TButton *Button195;
	TButton *Button196;
	TButton *Button197;
	TEdit *Edit16;
	TButton *Button200;
	TMenuItem *N20yever1;
	TCheckBox *CheckBox19;
	TRadioButton *RadioButton1;
	TRadioButton *RadioButton2;
	TMenuItem *check1;
	TRadioButton *RadioButton3;
	TTabSheet *TabSheet9;
	TWebBrowser *WebBrowser1;
	TButton *Button201;
	TComboBox *Serverlar;
	TRadioGroup *Karakter;
	TButton *Button202;
	TRadioGroup *RadioGroup1;
	TButton *Button203;
	TMemo *Memo3;
	TButton *Button204;
	TButton *Button205;
	TMenuItem *Pitman1;
	TRadioButton *RadioButton4;
	TRadioButton *RadioButton5;
	TMenuItem *Merchant1;
	TMenuItem *OpenBuy1;
	TButton *Button206;
	TEdit *Edit17;
	TRadioButton *RadioButton6;
	TClientSocket *ClientSocket4;
	TCheckBox *CheckBox20;
	TMenuItem *Inn1;
	TButton *Button207;
	TMenuItem *SendToInn01;
	TButton *Button208;
	TButton *Button209;
	TGroupBox *GroupBox24;
	TEdit *Edit18;
	TEdit *Edit19;
	TButton *Button210;
	TCheckBox *mapal;
	TCheckBox *matokal;
	TButton *Button211;
	TButton *Button212;
	TTimer *Timer8;
	TMenuItem *OpenSell1;
	TMenuItem *AddToSell1;
	TTimer *clock;
	TEdit *will_time_m;
	TEdit *will_time_h;
	TEdit *now_time_h;
	TEdit *now_time_m;
	TEdit *will2_time_h;
	TEdit *will2_time_m;
	void __fastcall FormCreate(TObject *Sender);
	void __fastcall AllPtOkClick(TObject *Sender);
	void __fastcall AllPtQuitClick(TObject *Sender);
	void __fastcall AllPressOkClick(TObject *Sender);
	void __fastcall AllTownClick(TObject *Sender);
	void __fastcall KazBaslaClick(TObject *Sender);
	void __fastcall KazDurClick(TObject *Sender);
	void __fastcall Button3Click(TObject *Sender);
	void __fastcall AddPtClick(TObject *Sender);
	void __fastcall SellItem2Click(TObject *Sender);
	void __fastcall SellAll1Click(TObject *Sender);
	void __fastcall SellItem1Click(TObject *Sender);
	void __fastcall CrashItem1Click(TObject *Sender);
	void __fastcall ConnectAll1Click(TObject *Sender);
	void __fastcall DisconnectAll1Click(TObject *Sender);
	void __fastcall ConClick(TObject *Sender);
	void __fastcall TownClick(TObject *Sender);
	void __fastcall CoordinateClick(TObject *Sender);
	void __fastcall CreatePtClick(TObject *Sender);
	void __fastcall QuitPtClick(TObject *Sender);
	void __fastcall Exit1Click(TObject *Sender);
	void __fastcall ListClick(TObject *Sender);
	void __fastcall Button5Click(TObject *Sender);
	void __fastcall ClientSocket1Read(TObject *Sender, TCustomWinSocket *Socket);
	void __fastcall SeciliLCekClick(TObject *Sender);
	void __fastcall EditSave(TObject *Sender);
	void __fastcall MemoSave(TObject *Sender);
	void __fastcall ComboSave(TObject *Sender);
	void __fastcall LeftHandClick(TObject *Sender);
	void __fastcall RightHandClick(TObject *Sender);
	void __fastcall MoveItemClick(TObject *Sender);
	void __fastcall GoRepairClick(TObject *Sender);
	void __fastcall radeConfirm1Click(TObject *Sender);
	void __fastcall AddThisItem1Click(TObject *Sender);
	void __fastcall AddMoney1Click(TObject *Sender);
	void __fastcall GiveList1Click(TObject *Sender);
	void __fastcall ItemIslem(TObject *Sender, TMouseButton Button,
	  TShiftState Shift, int X, int Y);
	void __fastcall SocketIslem(TObject *Sender);
	void __fastcall Sell2Click(TObject *Sender);
	void __fastcall Crash2Click(TObject *Sender);
	void __fastcall rade2Click(TObject *Sender);
	void __fastcall SellListKeyDown(TObject *Sender, WORD &Key, TShiftState Shift);
	void __fastcall CrashListKeyDown(TObject *Sender, WORD &Key,
          TShiftState Shift);
	void __fastcall TradeListKeyDown(TObject *Sender, WORD &Key,
		  TShiftState Shift);
		void __fastcall ListSave(TObject *Sender);
	void __fastcall CheckClick(TObject *Sender);
	void __fastcall giveskill(TObject *Sender);
	void __fastcall givestat(TObject *Sender);
	void __fastcall givestatall(TObject *Sender);
	void __fastcall st1jobClick(TObject *Sender);
	void __fastcall Button1Click(TObject *Sender);
	void __fastcall Button86Click(TObject *Sender);
	void __fastcall DolasClick(TObject *Sender);
	void __fastcall ListBoxttDblClick(TObject *Sender);
	void __fastcall PartyYp1Click(TObject *Sender);
	void __fastcall toSocketClick(TObject *Sender);
	void __fastcall BuffSkillListClickCheck(TObject *Sender);
	void __fastcall ClientSocket1Error(TObject *Sender, TCustomWinSocket *Socket,
          TErrorEvent ErrorEvent, int &ErrorCode);
	void __fastcall HealListClickCheck(TObject *Sender);
	void __fastcall Button79Click(TObject *Sender);
	void __fastcall DisconClick(TObject *Sender);
	void __fastcall GoToRepair1Click(TObject *Sender);
	void __fastcall GoPitman1Click(TObject *Sender);
	void __fastcall Start1Click(TObject *Sender);
	void __fastcall Stop1Click(TObject *Sender);
	void __fastcall GoPotion1Click(TObject *Sender);
	void __fastcall Timer2Timer(TObject *Sender);
	void __fastcall Button85Click(TObject *Sender);
	void __fastcall inngetirClick(TObject *Sender);
	void __fastcall Button87Click(TObject *Sender);
	void __fastcall Start2Click(TObject *Sender);
	void __fastcall Stop2Click(TObject *Sender);
	void __fastcall Timer3Timer(TObject *Sender);
	void __fastcall Button6Click(TObject *Sender);
	void __fastcall CheckBox1Click(TObject *Sender);
	void __fastcall Coordinate1Click(TObject *Sender);
	void __fastcall Start3Click(TObject *Sender);
	void __fastcall Stop3Click(TObject *Sender);
	void __fastcall AllTOwn1Click(TObject *Sender);
	void __fastcall Button82Click(TObject *Sender);
	void __fastcall RegisterClick(TObject *Sender);
	void __fastcall RAtackClick(TObject *Sender);
	void __fastcall RunToMobClick(TObject *Sender);
	void __fastcall CheckBox10Click(TObject *Sender);
	void __fastcall CheckBox11Click(TObject *Sender);
	void __fastcall distanceChange(TObject *Sender);
	void __fastcall hpcountChange(TObject *Sender);
	void __fastcall mpcountChange(TObject *Sender);
	void __fastcall Button11Click(TObject *Sender);
	void __fastcall Button90Click(TObject *Sender);
	void __fastcall MineXChange(TObject *Sender);
	void __fastcall MineYChange(TObject *Sender);
	void __fastcall UpdateSell(TObject *Sender);
	void __fastcall UpdateCrash(TObject *Sender);
	void __fastcall UpdateTrade(TObject *Sender);
	void __fastcall ListBox3DblClick(TObject *Sender);
	void __fastcall StopALl1Click(TObject *Sender);
	void __fastcall Button88Click(TObject *Sender);
	void __fastcall RadioGroup4Click(TObject *Sender);
	void __fastcall CheckBox9Click(TObject *Sender);
	void __fastcall Button89Click(TObject *Sender);
	void __fastcall SpeedSetChange(TObject *Sender);
	void __fastcall Button91Click(TObject *Sender);
	void __fastcall AtackTypeClick(TObject *Sender);
	void __fastcall skill0Click(TObject *Sender);
	void __fastcall skill5Click(TObject *Sender);
	void __fastcall skill6Click(TObject *Sender);
	void __fastcall skill7Click(TObject *Sender);
	void __fastcall skill8Click(TObject *Sender);
	void __fastcall RadioGroup1Click(TObject *Sender);
	void __fastcall SkillListDblClick(TObject *Sender);
	void __fastcall SelectedSkillsDblClick(TObject *Sender);
	void __fastcall SkillTimeChange(TObject *Sender);
	void __fastcall Button83Click(TObject *Sender);
	void __fastcall RadioGroup5Click(TObject *Sender);
	void __fastcall RadioGroup6Click(TObject *Sender);
	void __fastcall Button92Click(TObject *Sender);
	void __fastcall Button93Click(TObject *Sender);
	void __fastcall Timer1Timer(TObject *Sender);
	void __fastcall Potion1Click(TObject *Sender);
	void __fastcall AtackXChange(TObject *Sender);
	void __fastcall AtackYChange(TObject *Sender);
	void __fastcall CheckBox12Click(TObject *Sender);
	void __fastcall Helmet1Click(TObject *Sender);
	void __fastcall Pauldron1Click(TObject *Sender);
	void __fastcall Pads1Click(TObject *Sender);
	void __fastcall Bots1Click(TObject *Sender);
	void __fastcall Bots2Click(TObject *Sender);
	void __fastcall Earring01Click(TObject *Sender);
	void __fastcall Earring11Click(TObject *Sender);
	void __fastcall Pendant1Click(TObject *Sender);
	void __fastcall Belt1Click(TObject *Sender);
	void __fastcall Ring01Click(TObject *Sender);
	void __fastcall Ring1Click(TObject *Sender);
	void __fastcall Button84Click(TObject *Sender);
	void __fastcall buybowClick(TObject *Sender);
	void __fastcall Button134Click(TObject *Sender);
	void __fastcall Button135Click(TObject *Sender);
	void __fastcall Button136Click(TObject *Sender);
	void __fastcall Button137Click(TObject *Sender);
	void __fastcall Button138Click(TObject *Sender);
	void __fastcall Button139Click(TObject *Sender);
	void __fastcall Button140Click(TObject *Sender);
	void __fastcall Button181Click(TObject *Sender);
	void __fastcall ChatListClick(TObject *Sender);
	void __fastcall MesajChange(TObject *Sender);
	void __fastcall ChatTipiClick(TObject *Sender);
	void __fastcall Edit8Change(TObject *Sender);
	void __fastcall ClientSocket2Read(TObject *Sender, TCustomWinSocket *Socket);
	void __fastcall ClientSocket2Connect(TObject *Sender,
          TCustomWinSocket *Socket);
	void __fastcall ClientSocket2Error(TObject *Sender, TCustomWinSocket *Socket,
          TErrorEvent ErrorEvent, int &ErrorCode);
	void __fastcall Timer4Timer(TObject *Sender);
	void __fastcall ClientSocket3Read(TObject *Sender, TCustomWinSocket *Socket);
	void __fastcall Button183Click(TObject *Sender);
	void __fastcall Timer5Timer(TObject *Sender);
	void __fastcall CheckBox13Click(TObject *Sender);
	void __fastcall Button184Click(TObject *Sender);
	void __fastcall Button185Click(TObject *Sender);
	void __fastcall Button186Click(TObject *Sender);
	void __fastcall Button187Click(TObject *Sender);
	void __fastcall SocketReset1Click(TObject *Sender);
	void __fastcall alllocChange(TObject *Sender);
	void __fastcall allsrvChange(TObject *Sender);
	void __fastcall Memo1Change(TObject *Sender);
	void __fastcall CheckBox14Click(TObject *Sender);
	void __fastcall CheckBox15Click(TObject *Sender);
	void __fastcall proxyClick(TObject *Sender);
	void __fastcall CheckBox16Click(TObject *Sender);
	void __fastcall Button188Click(TObject *Sender);
	void __fastcall Button189Click(TObject *Sender);
	void __fastcall Button191Click(TObject *Sender);
	void __fastcall Button190Click(TObject *Sender);
	void __fastcall Timer6Timer(TObject *Sender);
	void __fastcall CheckBox17Click(TObject *Sender);
	void __fastcall Button192Click(TObject *Sender);
	void __fastcall CheckBox18Click(TObject *Sender);
	void __fastcall Timer7Timer(TObject *Sender);
	void __fastcall Button194Click(TObject *Sender);
	void __fastcall Button193Click(TObject *Sender);
	void __fastcall Button195Click(TObject *Sender);
	void __fastcall Button196Click(TObject *Sender);
	void __fastcall Button197Click(TObject *Sender);
	void __fastcall Button198Click(TObject *Sender);
	void __fastcall Button199Click(TObject *Sender);
	void __fastcall ClientSocket3Error(TObject *Sender, TCustomWinSocket *Socket,
          TErrorEvent ErrorEvent, int &ErrorCode);
	void __fastcall ClientSocket3Connect(TObject *Sender,
          TCustomWinSocket *Socket);
	void __fastcall Button200Click(TObject *Sender);
	void __fastcall N20yever1Click(TObject *Sender);
	void __fastcall RadioButton1Click(TObject *Sender);
	void __fastcall RadioButton2Click(TObject *Sender);
	void __fastcall check1Click(TObject *Sender);
	void __fastcall RadioButton3Click(TObject *Sender);
	void __fastcall Button201Click(TObject *Sender);
	void __fastcall Button202Click(TObject *Sender);
	void __fastcall Button203Click(TObject *Sender);
	void __fastcall Button204Click(TObject *Sender);
	void __fastcall Button205Click(TObject *Sender);
	void __fastcall Pitman1Click(TObject *Sender);
	void __fastcall RadioButton4Click(TObject *Sender);
	void __fastcall RadioButton5Click(TObject *Sender);
	void __fastcall OpenBuy1Click(TObject *Sender);
	void __fastcall Button206Click(TObject *Sender);
	void __fastcall RadioButton6Click(TObject *Sender);
	void __fastcall ClientSocket4Read(TObject *Sender, TCustomWinSocket *Socket);
	void __fastcall CheckBox20Click(TObject *Sender);
	void __fastcall SendToInn01Click(TObject *Sender);
	void __fastcall Button207Click(TObject *Sender);
	void __fastcall Button208Click(TObject *Sender);
	void __fastcall Button209Click(TObject *Sender);
	void __fastcall Edit18Change(TObject *Sender);
	void __fastcall Edit19Change(TObject *Sender);
	void __fastcall Button210Click(TObject *Sender);
	void __fastcall Button211Click(TObject *Sender);
	void __fastcall Button212Click(TObject *Sender);
	void __fastcall Timer8Timer(TObject *Sender);
	void __fastcall mapalClick(TObject *Sender);
	void __fastcall OpenSell1Click(TObject *Sender);
	void __fastcall AddToSell1Click(TObject *Sender);
	void __fastcall clockTimer(TObject *Sender);
private:	// User declarations
public:		// User declarations
	__fastcall TForm1(TComponent* Owner);

		void __fastcall MesajAl(tagMSG &Message) ;

};
//---------------------------------------------------------------------------
extern PACKAGE TForm1 *Form1;
//---------------------------------------------------------------------------
#endif
